#!/bin/sh
# Requirements: $USER added to wheel group and NetworkManager.service enabled.

cd $HOME

# Remove bash dotfiles
rm -rf .bash*

# Install essential packages
sudo pacman -S git neovim xclip kitty --noconfirm

# Install and enable SDDM
sudo pacman -S sddm --noconfirm
sudo systemctl enable sddm

# Install plasma and applications
sudo pacman -S nvidia nvidia-settings
sudo pacman -S plasma-desktop --nonconfirm
sudo pacman -S dolphin --nonconfirm

# Use zsh over bash
sudo pacman -S zsh --noconfirm
sudo chsh --shell /bin/zsh $USER

# Pull submodules
yadm submodule update --recursive --init

# Install yay
git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm && cd .. && rm -rf yay-bin

# Useful stuff
sudo pacman -S github-cli bitwarden --noconfirm

# Browser
yay -S brave-bin bitwarden --noconfirm

# Doom Emacs
sudo pacman -S emacs-nativecomp ripgrep fd
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
# doom install

# Fun stuff
sudo pacman -S neofetch
