#!/bin/sh
# Requirements: $USER added to wheel group and NetworkManager.service enabled.

cd $HOME

# Pull submodules
yadm submodule update --recursive --init

# Install yay
sudo pacman -S base-devel git --noconfirm && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm && cd .. && rm -rf yay-bin

# Terminal emulator, shell and vim
yay -S kitty neovim xclip zsh antigen
sudo chsh --shell /bin/zsh $USER

# Texteditor
sudo pacman -S emacs-nativecomp ripgrep fd
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
# doom install

# Install and enable SDDM
sudo pacman -S sddm --noconfirm
sudo systemctl enable sddm

# Install plasma and applications
sudo pacman -S nvidia nvidia-settings
sudo pacman -S plasma-desktop --nonconfirm
yay -S dolphin brave-bin bitwarden --nonconfirm

# Other
yay -S neofetch github-cli

# Remove bash dotfiles, the last .bash_history has to be removed manually
rm -rf .bash*
