#!/bin/sh
# Requirements: $USER added to wheel group and NetworkManager.service enabled.

cd $HOME

# Pull submodules
yadm submodule update --recursive --init

# Install yay
sudo pacman -S base-devel git --noconfirm && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm && cd .. && rm -rf yay-bin

# Terminal emulator, shell and vim
yay -S kitty neovim xclip zsh antigen --noconfirm
sudo chsh --shell /bin/zsh $USER

# Texteditor
sudo pacman -S emacs-nativecomp ripgrep fd --noconfirm
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
# doom install

# Install and enable SDDM
sudo pacman -S sddm --noconfirm
sudo systemctl enable sddm

# Install plasma and applications
sudo pacman -S nvidia nvidia-settings --noconfirm
sudo pacman -S plasma --noconfirm
yay -S dolphin brave-bin bitwarden ark --noconfirm

# Test out 
yay -S kvantum latte-dock papirus-icon-theme --noconfirm
yay -S layan-kde-git layan-gtk-theme-git kvantum-theme-layan-git --noconfirm

# Other
yay -S neofetch github-cli --noconfirm

# Remove bash dotfiles, the last .bash_history has to be removed manually
rm -rf .bash*
