#!/bin/zsh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gvim desktop=0 follow=on
bspc rule -a RStudio desktop=0 follow=on
bspc rule -a Google-chrome desktop=2 follow=on
