[default.files]
".config/git" = "~/.config/git"
".config/kitty" = "~/.config/kitty"

[emacs.files]
".emacs.d" = "~/.emacs.d"

[vim.files]
".vimrc" = "~/.vimrc"
".gvimrc" = "~/.gvimrc"
".config/nvim" = "~/.config/nvim"

[zsh.files]
".zprofile" = "~/.zprofile"
".zshrc" = "~/.zshrc"
".zshenv" = "~/.zshenv"
".zimrc" = "~/.zimrc"

[macos.files]
".config/karabiner" = "~/.config/karabiner"
